### ISSUE TITLE
Question on whether movie-len 100k suits this list-wise recommendation task.

### ISSUE THREAD

**Issue by yurunsheng1** [egipcy/LIRD#1]
Hi,

First thank you so much for providing us this excellent code!

I am wondering whether Movie-len 100k is a suitable dataset for this task? Since the Movie-len 100k does not consider any long-term behavior for the user (user only rated for each movie individually). 

Therefore, I am concerned about if it is not good enough for the list-wise recommendation task which focus on the user long-term behavior.

Looking forwards to your reply!

Runsheng

**Comment by egipcy** [comment]
Hi,

Thanks for your interest.

Before I started coding, the idea was to compare this upgraded DQN to a basic DQN in terms of diversity of recommendations, as this was not clearly shown to me when I first read the paper. Since I am interested in films, if I wasn't able to come with a good metric, I would probably be able to evaluate the diversity myself. I sadly didn't have time to exhibit differences if any, I just had time to make it work. Whatever.

Getting to your question, yes, MovieLens is not adequate to show any long-term benefits. But I guess this question has been clearly answered for all DQNs by older papers (and recalled Figure 4 and section 3.2 in this paper) as it rely on the gamma factor in the Bellman equation.

Feel free to use the code on another dataset if you want to show long-term behaviors. And feel free to ask me questions if you have difficulties adapting the code.

Amaury

**Comment by yurunsheng1** [comment]
Thanks so much!

I will test it on another dataset and tell you once I get some useful results.

**Comment by wkzqn** [comment]
@yurunsheng1 
Hello, may I ask if you have problems running the author's code? When I train the model, reward will not increase, and finally I will not get the histogram of the author. Thank you very much and look forward to your reply.

**Comment by wkzqn** [comment]
@yurunsheng1 
Looking forward to your reply, can I have any way to contact you?

**Comment by My-captain** [comment]
> @yurunsheng1
> Looking forward to your reply, can I have any way to contact you?
铁子，你最后是如何解决的？
我跑了作者的代码，训练MovieEmbedding的时候，发现在测试集上的accuracy只有2%.....
```shell
3125/3125 [==============================] - 11s 3ms/step - loss: 0.2579 - accuracy: 0.9657
[MovieEmbedding]Train set: Loss=0.2579 ; Accuracy=96.6%
3125/3125 [==============================] - 10s 3ms/step - loss: 33.9379 - accuracy: 0.0201
[MovieEmbedding]Test set: Loss=33.9379 ; Accuracy=2.0%
```

**Comment by My-captain** [comment]
@wkzqn 

铁子，你最后是如何解决的？
我跑了作者的代码，训练MovieEmbedding的时候，发现在测试集上的accuracy只有2%.....
```shell
3125/3125 [==============================] - 11s 3ms/step - loss: 0.2579 - accuracy: 0.9657
[MovieEmbedding]Train set: Loss=0.2579 ; Accuracy=96.6%
3125/3125 [==============================] - 10s 3ms/step - loss: 33.9379 - accuracy: 0.0201
[MovieEmbedding]Test set: Loss=33.9379 ; Accuracy=2.0%
```
